create table if not exists public.app_state (
  user_id uuid primary key references auth.users (id) on delete cascade,
  state jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.daily_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  record_date date not null,
  workout_done boolean not null default false,
  diet_done boolean not null default false,
  updated_at timestamptz not null default now(),
  unique (user_id, record_date)
);

alter table public.app_state enable row level security;
alter table public.daily_logs enable row level security;

create policy "Users can read own app state"
  on public.app_state for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can insert own app state"
  on public.app_state for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update own app state"
  on public.app_state for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own app state"
  on public.app_state for delete
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can read own daily logs"
  on public.daily_logs for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can insert own daily logs"
  on public.daily_logs for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update own daily logs"
  on public.daily_logs for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own daily logs"
  on public.daily_logs for delete
  to authenticated
  using (auth.uid() = user_id);
